language: c++

include:
    - os: linux
      env:
          - TARGET=x86_64-unkown-linux-gnu
          - EVAL_CXX="CC=gcc-8 && CXX=g++-8"
      addons:
          apt:
              update: true
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - cmake
                  - g++-8
                  - libsdl2-dev
      compiler: g++-8
    - os: linux
      env:
          - TARGET=x86_64-unkown-linux-gnu
          - EVAL_CXX="CC=clang-7 && CXX=clang++-7"
      addons:
          apt:
              update: true
              sources:
                  - llvm-toolchain-trusty-7
                  - ubuntu-toolchain-r-test
              packages:
                  - cmake
                  - clang-7
                  - libstdc++-7-dev
                  - libsdl2-dev
      compiler: clang++-7
    - os: osx
      osx_image: xcode10.2
      env:
          - EVAL_CXX="brew install gcc; brew link --overwrite gcc && CC=gcc && CXX=g++"
      compiler: g++
    - os: osx
      osx_image: xcode10.2
      compiler: clang++

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi

script:
    - mkdir build
    - cd build
    - eval "${EVAL_CXX}"
    - ls /usr/include | grep -i "sdl"
    - cmake -DCMAKE_PREFIX_PATH=~/usr/include ..
    - make -j$(nproc)
    - ./CMakeGen

#notifications:
#   email:
#       on_success: never
#       on_failure: change

