image: Visual Studio 2019

platform:
    - Win32
    - x64

configuration:
    - Debug
    - Release

matrix:
    fast_finish: false

init:
    - cmd: cmake --version
    - cmd: msbuild /version

before_build:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=%configuration% ..

build:
    project: build/CMakeGen.sln
    parallel: true
    verbosity: minimal

